### ISSUE TITLE
Ed25519 Support?

### ISSUE THREAD

**Issue by SolomonSklash** [solokeys/openpgp#3]
I am curious if the Solo OpenPGP firmware will support Ed25519 curves? This is my biggest issue with Yubikeys, I've contacted them and they do not have a roadmap for adding it.

I'd much prefer to use my Solo full time, and once it has GPG support I will be able to, and ideally it would support Ed25519.

**Comment by nickray** [comment]
We intend to support Ed25519. Issue is that OpenPGP Card (the "smartcard" app) does not specify it, similar to how SSH does support 25519 keys but not its PKCS#11 interface. Worst case it will be a vendor extension. Some inofficial work on the crypto implementation has started in https://github.com/nickray/salty.

**Comment by 0x0ece** [comment]
@SolomonSklash what's your use case, just gpg or ssh as well? Can you explain us what other tools you may be looking at?

If you check out, in our campaign we tried to explain the current issues we know of with Ed25519:
https://www.crowdsupply.com/solokeys/somu
(at the end, section "How Can I Be More Involved?")

Knowing what people want/need may help us prioritize.

**Comment by SolomonSklash** [comment]
@0x0ece I use my Yubikey for U2F, HMAC challenge-response, normal GPG usage, as well as SSH via gpg-agent. I used it for SSH via PIV/smartcard feature in the past as well, before I switched to GPG subkeys for SSH.

I somehow missed the stretch goals on the Somu adding Ed25519 and SSH. I've backed it and hope those goals are met.

**Comment by nickray** [comment]
@SolomonSklash off-topic, but curious as to why you switched from PIV to GPG keys?

**Comment by SolomonSklash** [comment]
@nickray I switched because I wanted to setup GPG anyway. I still keep PIV as a backup just in case, but having everything tied to GPG makes things simpler.

**Comment by nickray** [comment]
@SolomonSklash you may be the right person to give our "HMAC-SHA-256" challenge-response a spin: https://github.com/solokeys/solo-python/#challenge-response; if you don't mind my asking, what are your use cases for the Yubico HMAC-SHA1 version? Advantage of using WebAuthn's `hmac-secret` would be that it's not proprietary (most keys will support `hmac-secret` due to Windows using this), so I'm pondering useful integrations.

**Comment by nickray** [comment]
https://github.com/nickray/salty/blob/main/c-api/salty.h is ready for testing. Only Ed25519 signatures so far.

**Comment by mightybyte** [comment]
I would also love to see ED25519 support on a SoloKey.  In particular, my use case needs the ability to generate raw ED25519 signatures.  I'm not sure whether OpenPGP is sufficient because from what I've seen it looks like it handles the hashing automatically . For my application I would like to have the ability to calculate raw signatures with no hashing step.

**Comment by lf94** [comment]
@nickray when you mean "ready for testing", is this a signal to someone or anyone to implement it into the `solo` project?

**Comment by nickray** [comment]
Yes :) The tricky part (I think) would be to extend the RK storage which assumes just one curve.

**Comment by lf94** [comment]
RK?

**Comment by michaelblyons** [comment]
> RK? R.... Key....

@If94 I'm not 100% sure, but I believe that means [resident key](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Resident_Keys.html).

**Comment by RA80533** [comment]
@merlokk This can be closed since it was implemented in e0f8bfa.
